### ISSUE TITLE
Please help me solve "mvn install error" 

### ISSUE THREAD

**Issue by DSRYU** [macarthur-lab/matchbox#51]
Good morning.

I would like to install matchbox on my ubuntu server.
For the matchbox installation, I am following the instructions in README.md.
The java sdk (1.8.0_144) and maven (3.5.0) tools have been successfully installed and the shell environment variables (JAVAHOME, PATH, CLASSPATH) appear to already be specified.

However, the following error occurs when I run the third command (" mvn clean install ") in the matchbox directory after the git cloning.

[ERROR] Failed to execute goal on project matchbox: Could not resolve dependencies for project org.broadinstitute.macarthurlab:matchbox:jar:0.1.0: The following artifacts could not be resolved: org.monarchinitiative:exomiser-spring-boot-starter:jar:7.3.0-SNAPSHOT, org.monarchinitiative:exomiser-spring-boot-test:jar:7.3.0-SNAPSHOT: Could not find artifact org.monarchinitiative:exomiser-spring-boot-starter:jar:7.3.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

It seems like either the matchbox repository does not provide dependent library or I did something wrong.
Would you mind helping me solve this problem, please?

Also, are you planning to provide the docker version of the platform based on Ubuntu's latest image?

Thank you very much.

**Comment by northwestwitch** [comment]
Hi! I'm trying to install matchbox via Docker and I get the same error message. How did you solve this issue? Thanks!

**Comment by harindra-a** [comment]
Hi , did you try this method (with Docker)? That is definitely a Exomiser version error (they are in 10+ now). Looks like you might be not using the current code, 

https://github.com/macarthur-lab/matchbox/tree/master/deploy/docker/with_data_mounted_to_container

(I would use the master branch too if you are not using it already)

**Comment by northwestwitch** [comment]
So far I've tried the other Docker method (it said easiest! :) ). I'll try the other now. Thanks!

**Comment by harindra-a** [comment]
oh sorry, yes, 

https://github.com/macarthur-lab/matchbox/tree/master/deploy/docker/with_data_in_container

is easier. I will try it on my machine and see if I get errors

**Comment by harindra-a** [comment]
Actually, I found a bug sorry! We have two versions of this Docker (for standalone, and as part of another system (seqr)). Looks like the other Docker file was updated with changes to Exomiser version and not this. I will adjust this and let you know

**Comment by northwestwitch** [comment]
Thanks! :)
