### ISSUE TITLE
Error while deploying using Docker (both methods)

### ISSUE THREAD

**Issue by northwestwitch** [macarthur-lab/matchbox#53]
Hi! We had a short exchange about this on another issue (#51). Don't know if you are working on this but I tested today and the installation with Docker (with data in container) still gives this error:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.643 s
[INFO] Finished at: 2018-10-15T08:36:26+00:00
[INFO] Final Memory: 17M/165M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project matchbox: Could not resolve dependencies for project org.broadinstitute.macarthurlab:matchbox:jar:0.1.0: The following artifacts could not be resolved: org.monarchinitiative.exomiser:exomiser-spring-boot-starter:jar:10.1.0, org.monarchinitiative.exomiser:exomiser-spring-boot-test:jar:10.1.0: Could not find artifact org.monarchinitiative.exomiser:exomiser-spring-boot-starter:jar:10.1.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
The command '/bin/sh -c $MVN -Dmaven.test.skip=true clean install package' returned a non-zero code: 1

I'll test with other Docker method now!

**Comment by northwestwitch** [comment]
Additionally, the address where to download the seqr reference data has changed, so I think in the readme of the installer with data mounted to container should be changed from:

`wget https://storage.googleapis.com/seqr-reference-data/1711_phenotype.tar.gz` to 

`wget https://storage.googleapis.com/seqr-reference-data/1807_phenotype.tar.gz`

**Comment by DSRYU** [comment]
@northwestwitch 

Hello.

I also got same error message during updating new release matchbox.

The used matchbox version is **with_data_mounted_to_container** and the reference directory details are as follows:
ls -al /data/reference_data/
total 16
drwxr-xr-x 4 rarebird rarebird 4096 11월  8 18:08 .
drwxr-xr-x 3 root     root     4096 11월  8 18:13 ..
drwxrwx--- 3 rarebird rarebird 4096  7월 27 12:40 1807_phenotype
drwxrwxrwx 3 rarebird rarebird 4096  8월  7  2017 exomiser-cli-8.0.0

When docker image is building, I got the same error for "cannot find symbol , symbol:   variable Mockito" as follows. I also got same error when I tried to install matchbox using another docker version image.


[INFO] 4 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 59.763 s
[INFO] Finished at: 2018-11-08T09:28:36+00:00
[INFO] Final Memory: 40M/329M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project matchbox: Compilation failure: Compilation failure:
[ERROR] /Exomiser/matchbox/src/main/java/org/broadinstitute/macarthurlab/matchbox/config/ExomiserConfig.java:[3,19] package org.mockito does not exist
[ERROR] /Exomiser/matchbox/src/main/java/org/broadinstitute/macarthurlab/matchbox/config/ExomiserConfig.java:[23,17] cannot find symbol
[ERROR] symbol:   variable Mockito
[ERROR] location: class org.broadinstitute.macarthurlab.matchbox.config.ExomiserConfig
[ERROR] /Exomiser/matchbox/src/main/java/org/broadinstitute/macarthurlab/matchbox/config/ExomiserConfig.java:[24,17] cannot find symbol
[ERROR] symbol:   variable Mockito
[ERROR] location: class org.broadinstitute.macarthurlab.matchbox.config.ExomiserConfig
[ERROR] /Exomiser/matchbox/src/main/java/org/broadinstitute/macarthurlab/matchbox/config/ExomiserConfig.java:[25,17] cannot find symbol
[ERROR] symbol:   variable Mockito
[ERROR] location: class org.broadinstitute.macarthurlab.matchbox.config.ExomiserConfig
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
The command '/bin/sh -c $MVN -Dmaven.test.skip=true clean install package' returned a non-zero code: 1

**Comment by northwestwitch** [comment]
Hi! This has not been fixed yet, but I've found a workaround to get a functioning version of the server:

- Installed using maven (https://github.com/macarthur-lab/matchbox/tree/master/deploy/maven)

- I've added this specific dependency to the pom-xml file:

```
<!-- https://mvnrepository.com/artifact/org.mockito/mockito-core -->
    <dependency>
       <groupId>org.mockito</groupId>
       <artifactId>mockito-all</artifactId>
       <version>2.0.2-beta</version>
   </dependency>
```

- I've modified a test that was failing and prevented the build upon failure. It's this one in orange:
![image](https://user-images.githubusercontent.com/28093618/48264904-668c5680-e42b-11e8-8eae-d7940c7a27be.png)

The problem is that the specific created query is not recognized by the API, so it's used a generic query that returns another number instead. I didn't want to enter into the specifics of the API so I've just fixed the test to match the result of the general query. 

To fix it in this way you should change the last line in **testGeneSymbolWithNoVariantInfoMatchOnly** test into:
```
assertThat(df.format(genotypeSimilarityScore.getScore()), equalTo("0.94"));
```

After these fixed Maven compiles and the server runs as it should!

**Comment by northwestwitch** [comment]
Ah and remember to use the reference data 1807 when you set up Exomiser (look above in this issue).
Good luck!
