### ISSUE TITLE
It also gives error (mvn version installation)

### ISSUE THREAD

**Issue by DSRYU** [macarthur-lab/matchbox#56]
Hello,

I am trying to install **using maven**.
This version also gives the error as below messages:

[ERROR] Failed to execute goal on project matchbox: Could not resolve dependencies for project org.broadinstitute.macarthurlab:matchbox:jar:0.1.0: The following artifacts could not be resolved: org.monarchinitiative.exomiser:exomiser-spring-boot-starter:jar:11.0.0, org.monarchinitiative.exomiser:exomiser-spring-boot-test:jar:11.0.0: Could not find artifact org.monarchinitiative.exomiser:exomiser-spring-boot-starter:jar:11.0.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**The version of maven** is Apache Maven 3.3.9 .
root@ubuntu:~/.m2/matchbox# mvn -version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_181, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: ko_KR, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-96-generic", arch: "amd64", family: "unix"

**The Exomiser directory structure** is  as follows:
root@ubuntu:~/.m2# tree -L 1 Exomiser
Exomiser
├── 1807_phenotype
├── 1807_phenotype.tar.gz
├── LICENCE
├── LOGO_IRDIRCRR_RVB.jpg
├── README.md
├── docs
├── exomiser-cli
├── exomiser-core
├── exomiser-data-genome
├── exomiser-data-phenotype
├── exomiser-rest-prioritiser
├── exomiser-spring-boot-autoconfigure
├── exomiser-spring-boot-starter
├── exomiser-spring-boot-test
├── exomiser-web
├── mvnw
├── mvnw.cmd
└── pom.xml

I also edited the part of  **application.properties file**.
root@ubuntu:~/.m2# vi matchbox/src/main/resources/application.properties

matchbox.gene-symbol-to-id-mappings=${user.dir}/config/gene_symbol_to_ensembl_id_map.txt
matchbox.connected-nodes=${user.dir}/config/nodes.json
exomiser.data-directory=/home/sysadm/.m2/Exomiser
exomiser.phenotype.data-version=1807

 I used **below command** for installation.
root@ubuntu:~/.m2/matchbox# mvn clean install package

Could you help me?

**Comment by northwestwitch** [comment]
I remember experiencing an error like this.. 

After cloning Exomiser have you installed it? 
```mvn clean install package```
from inside the cloned repo?

**Comment by DSRYU** [comment]
I tried it but it gives error.
root@ubuntu:/data/reference_data/Exomiser# ls -al ~/.m2/
total 12
drwxr-xr-x  2 root   root   4096 11월 22 18:29 .
drwxr-xr-x 18 sysadm sysadm 4096 11월 22 18:31 ..
-rw-r--r--  1 root   root     86 11월 22 18:29 settings.xml
setting.xml
< settings>
<localRepository>${user.home}/.m2/repository</localRepository>
</settings>

root@ubuntu:/data/reference_data/Exomiser# ls -al
total 228
drwxr-xr-x 15 root root  4096 11월 22 18:31 .
drwxr-xr-x  3 root root  4096 11월 22 18:28 ..
drwxr-xr-x  2 root root  4096 11월 22 18:28 .circleci
drwxr-xr-x  8 root root  4096 11월 22 18:28 .git
-rw-r--r--  1 root root   447 11월 22 18:28 .gitattributes
-rw-r--r--  1 root root   841 11월 22 18:28 .gitignore
drwxr-xr-x  3 root root  4096 11월 22 18:28 .mvn
-rw-r--r--  1 root root 34519 11월 22 18:28 LICENCE
-rw-r--r--  1 root root 83957 11월 22 18:28 LOGO_IRDIRCRR_RVB.jpg
-rw-r--r--  1 root root  9366 11월 22 18:28 README.md
drwxr-xr-x  2 root root  4096 11월 22 18:28 docs
drwxr-xr-x  4 root root  4096 11월 22 18:28 exomiser-cli
drwxr-xr-x  5 root root  4096 11월 22 18:31 exomiser-core
drwxr-xr-x  4 root root  4096 11월 22 18:28 exomiser-data-genome
drwxr-xr-x  4 root root  4096 11월 22 18:28 exomiser-data-phenotype
drwxr-xr-x  4 root root  4096 11월 22 18:28 exomiser-rest-prioritiser
drwxr-xr-x  4 root root  4096 11월 22 18:28 exomiser-spring-boot-autoconfigure
drwxr-xr-x  4 root root  4096 11월 22 18:28 exomiser-spring-boot-starter
drwxr-xr-x  4 root root  4096 11월 22 18:28 exomiser-spring-boot-test
drwxr-xr-x  4 root root  4096 11월 22 18:28 exomiser-web
-rw-r--r--  1 root root  6468 11월 22 18:28 mvnw
-rw-r--r--  1 root root  4994 11월 22 18:28 mvnw.cmd
-rw-r--r--  1 root root 11680 11월 22 18:28 pom.xml

root@ubuntu:/data/reference_data/Exomiser# mvn clean install package
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] exomiser ........................................... SUCCESS [  0.570 s]
[INFO] exomiser-core ...................................... FAILURE [  9.206 s]
[INFO] exomiser-spring-boot-autoconfigure ................. SKIPPED
[INFO] exomiser-spring-boot-starter ....................... SKIPPED
[INFO] exomiser-spring-boot-test .......................... SKIPPED
[INFO] exomiser-cli ....................................... SKIPPED
[INFO] exomiser-data-genome ............................... SKIPPED
[INFO] exomiser-data-phenotype ............................ SKIPPED
[INFO] exomiser-rest-prioritiser .......................... SKIPPED
[INFO] exomiser-web ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.598 s
[INFO] Finished at: 2018-11-22T18:37:50+09:00
[INFO] Final Memory: 52M/656M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project exomiser-core: There are test failures.
[ERROR]
[ERROR] Please refer to /data/reference_data/Exomiser/exomiser-core/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /data/reference_data/Exomiser/exomiser-core && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java '-javaagent:/root/.m2/repository/org/jacoco/org.jacoco.agent/0.8.1/org.jacoco.agent-0.8.1-runtime.jar=destfile=/data/reference_data/Exomiser/exomiser-core/target/jacoco.exec,excludes=**/resources/**:**/assemble/**' -jar /data/reference_data/Exomiser/exomiser-core/target/surefire/surefirebooter3160720047109604265.jar /data/reference_data/Exomiser/exomiser-core/target/surefire 2018-11-22T18-37-49_419-jvmRun1 surefire4075254641124906505tmp surefire_05707736014213914957tmp
[ERROR] Error occurred in starting fork, check output in log
....
[ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /data/reference_data/Exomiser/exomiser-core && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java '-javaagent:/root/.m2/repository/org/jacoco/org.jacoco.agent/0.8.1/org.jacoco.agent-0.8.1-runtime.jar=destfile=/data/reference_data/Exomiser/exomiser-core/target/jacoco.exec,excludes=**/resources/**:**/assemble/**' -jar /data/reference_data/Exomiser/exomiser-core/target/surefire/surefirebooter2589335864457829238.jar /data/reference_data/Exomiser/exomiser-core/target/surefire 2018-11-22T18-31-52_099-jvmRun2 surefire607711632266005679tmp surefire_26777377948123787022tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:671)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.access$600(ForkStarter.java:115)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:362)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:342)
[ERROR] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ERROR] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[ERROR] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[ERROR] at java.lang.Thread.run(Thread.java:748)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]

**Comment by northwestwitch** [comment]
Hi again. Under the ~/.m2/ folder I have these settings:
```
<settings>
 		<localRepository>${user.home}/.m3/repository</localRepository>
</settings>
```
Maybe this helps?

**Comment by julesjacobsen** [comment]
You're running whatever maven version is installed on your system. This can cause problems, so Exomiser has a bundled maven binary to prevent these issues. Run it like this:
```bash
./mvnw clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
```

**Comment by DSRYU** [comment]
Thank northwestwitch for kind reply.

Dear julesjacobsen.

You're right.
-DskipTests enable to compile Exomiser.

Thanks again ^^.


INFO] Reactor Summary:
[INFO]
[INFO] exomiser ........................................... SUCCESS [  3.849 s]
[INFO] exomiser-core ...................................... SUCCESS [ 11.169 s]
[INFO] exomiser-spring-boot-autoconfigure ................. SUCCESS [ 39.635 s]
[INFO] exomiser-spring-boot-starter ....................... SUCCESS [  0.032 s]
[INFO] exomiser-spring-boot-test .......................... SUCCESS [  0.149 s]
[INFO] exomiser-cli ....................................... SUCCESS [ 42.698 s]
[INFO] exomiser-data-genome ............................... SUCCESS [ 43.924 s]
[INFO] exomiser-data-phenotype ............................ SUCCESS [  4.553 s]
[INFO] exomiser-rest-prioritiser .......................... SUCCESS [ 45.370 s]
[INFO] exomiser-web ....................................... SUCCESS [ 19.012 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

**Comment by DSRYU** [comment]
Thanks to julesjacobsen, the Exomiser has been  successfully compiled.
But I have another error in compiling matchbox with mvn.

I edited pom.xml and GenotypeSimilarityServiceImplTest.java as recommended:
The added infromation in pom.xml is like this(In the case of 1.9.5 version, I tried both cases, commetend or uncommented):
               <dependency>
                    <groupId>org.mockito</groupId>
                    <artifactId>mockito-all</artifactId>
                    <version>1.9.5</version>
                    <scope>test</scope>
                </dependency>

                <dependency>
                        <groupId>org.mockito</groupId>
                        <artifactId>mockito-all</artifactId>
                        <version>2.0.2-beta</version>
                </dependency>
But matchbox maven could not recognize GenotypeSimilarityServiceImplTest class.
The edited GenotypeSimilarityServiceImplTest.java is like this:
       //assertThat(commonGenes, equalTo(expected));
	DecimalFormat df = new DecimalFormat("0.##");
        assertThat(df.format(genotypeSimilarityScore.getScore()), equalTo("0.94"));

**before editing GenotypeSimilarityServiceImplTest.java, it gives below error**:

[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ matchbox ---
[INFO] Surefire report directory: /home/sysadm/matchbox/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
오류: 기본 클래스 org.apache.maven.surefire.booter.ForkedBooter을(를) 찾거나 로드할 수 없습니다.
==> This means "Error: basic class, org.apache.maven.surefire.booter.ForkedBooter is not founded or loaded.
Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.277 s
[INFO] Finished at: 2018-11-23T13:41:36+09:00
[INFO] Final Memory: 37M/284M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project matchbox: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/sysadm/matchbox && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar /home/sysadm/matchbox/target/surefire/surefirebooter6380962758114387402.jar /home/sysadm/matchbox/target/surefire/surefire5390621855385802781tmp /home/sysadm/matchbox/target/surefire/surefire_06289007752142453377tmp
[ERROR] -> [Help 1]
[ERROR]


Could you look at this more?


[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project matchbox: Compilation failure
[ERROR] /home/sysadm/matchbox/src/test/java/org/broadinstitute/macarthurlab/matchbox/match/GenotypeSimilarityServiceImplTest.java:[173,30] cannot find symbol
[ERROR] symbol:   variable genotypeSimilarityScore
[ERROR] location: class org.broadinstitute.macarthurlab.matchbox.match.GenotypeSimilarityServiceImplTest
[ERROR] -> [Help 1]

**Comment by northwestwitch** [comment]
About the failing test, It's due to a bug that I described in another issue (#54) and has to be fixed before having a full functioning version of the software. But if you want to install Matchbox to test it you should modify this test first, otherwise it doesn't install.

**Comment by DSRYU** [comment]
Thanks northwestiwitch.

About the matchbox compile, it has been successfully compiled without test process.
When I run the compiled matchbox with below command, it gave other errors like belows:
root@ubuntu:~/matchbox#  java -jar target/matchbox-0.1.0.jar --server.port=9020
I think it would be caused by **converting modules** gene symbols to ensembl id.
How can I solve it?
Best regards,
2018-11-26 16:24:25.446  INFO 12055 --- [           main] o.m.e.a.DataDirectoryAutoConfiguration   : Exomiser data directory set to: /data/reference_data/Exomiser
2018-11-26 16:24:25.471  INFO 12055 --- [           main] com.zaxxer.hikari.HikariDataSource       : exomiser-phenotype-1807 - Started.
2018-11-26 16:24:25.919 ERROR 12055 --- [           main] o.b.m.matchbox.metrics.BaseMetric        : Error reading gene symbol to emsembl id map:java.lang.NullPointerException : null

....
2018-11-26 16:24:26.441  INFO 12055 --- [           main] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:2, serverValue:26}] to 147.47.106.196:27017
2018-11-26 16:24:26.493 ERROR 12055 --- [           main] o.b.m.matchbox.metrics.BaseMetric        : Error reading gene symbol to emsembl id map:java.lang.NullPointerException : null
2018-11-26 16:24:26.496 ERROR 12055 --- [           main] o.b.m.matchbox.metrics.BaseMetric        : Error reading gene symbol to emsembl id map:java.lang.NullPointerException : null
2018-11-26 16:24:26.511  INFO 12055 --- [           main] o.b.m.m.config.MatchMakerNodeConfig      : Reading MME nodes from /home/sysadm/matchbox/config/nodes.json

**Comment by northwestwitch** [comment]
Hi, I see the same error when I launch the server. I don't know what the cause!
